name: 🧪 deploy 🧪

on:
  workflow_run:
    workflows: ["Main file"]
    types:
      - completed

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener información de la rama
        run: |
          echo "${{inputs.environment}}"

