name: 🧪 E2E 🧪

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: 📥 Install Dependencies
        run: npm install

      - name: 📥 Set up .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ inputs.environment }}" >> .env

      - name: 🧪 E2E 🧪
        run: npm run test:e2e