name: 🧪 E2E TEST 🧪

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 E2E 🧪
        run: npm run test:ci
