name: 🧪 Unit test and E2E 🧪

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  common_steps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Install Dependencies
        run: npm install

      - name: 📥 Set up envs
        run: echo "${{ secrets.ENV_FILE }}" > .env

  unit_tests:
    runs-on: ubuntu-latest
    needs: common_steps
    steps:
      - name: 🧪 UNIT'
        run: npm run test:ci

  e2e_tests:
    runs-on: ubuntu-latest
    needs: [common_steps, unit_tests]
    steps:
      - name: 🧪 E2E
        run: npm run test:e2e
