name: Main file
on:
  push:
    branches: ['main' , 'development', 'qa']
env:
  PROJECT_NAME: nest
jobs:
  unit:
    uses: Luiggi13/deployment/.github/workflows/unit.yaml@main
    with:
      environment: ${GITHUB_REF#refs/heads/}
  e2e:
    uses: Luiggi13/deployment/.github/workflows/e2e.yaml@main
    with:
      environment: ${GITHUB_REF#refs/heads/}
  deploy:
      runs-on: ubuntu-latest
      needs: [unit,e2e]
      steps:
        - name: Obtener información de la rama
          run: |
            case "${GITHUB_REF#refs/heads/}" in
              "main")
                PROJECT_NAME="nest-${GITHUB_REF#refs/heads/}"
                echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
                echo "la variable se llamará $PROJECT_NAME"
                ;;
              "qa")
                echo "qa"
                ;;
              "development")
                echo "development"
                ;;
              *)
                echo "Otro entorno"
                ;;
            esac