name: Tests CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  common_steps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Set up .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

  unit_tests:
    runs-on: ubuntu-latest
    needs: common_steps
    env:
      WORKING_DIRECTORY: ${{ github.workspace }}
    steps:
      - name: Run UNIT tests
        run: npm run test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  e2e_tests:
    runs-on: ubuntu-latest
    needs: [common_steps, unit_tests]
    env:
      WORKING_DIRECTORY: ${{ github.workspace }}
    steps:
      - name: Run E2E tests
        run: npm run test:ci
        working-directory: ${{ env.WORKING_DIRECTORY }}
