name: Testing backend

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 UNIT 🧪
        uses: ./.github/unit_tests.yaml

        run: npm run test:ci

  e2e_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: 🧪 E2E 🧪
        uses: ./.github/e2e_tests.yaml
